// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FloorAreaTable from "./FloorAreaTable.bs.js";

function Index(Props) {
  return React.createElement("div", {
              className: "mx-16"
            }, React.createElement("div", {
                  id: "top-buttons"
                }, React.createElement("button", {
                      className: "text-black dark:text-white p-4"
                    }, "Add")), React.createElement("div", {
                  id: "table-container"
                }, React.createElement(FloorAreaTable.make, {})));
}

var make = Index;

export {
  make ,
  
}
/* react Not a pure module */
