// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Login$LoginForm(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setUsername = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setPassword = match$1[1];
  var usernameChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(setUsername, (function (_prev) {
                  return value;
                }));
  };
  var passwordChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(setPassword, (function (_prev) {
                  return value;
                }));
  };
  return React.createElement("div", {
              className: "inline-block align-bottom bg-gray-400 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full"
            }, React.createElement("form", {
                  className: "flex flex-col flex-wrap px-8 pt-6 pb-8 mb-4 bg-gray-300"
                }, React.createElement("div", {
                      className: "m-4"
                    }, React.createElement("label", {
                          className: "table-cell text-black",
                          htmlFor: "username"
                        }, "Username: "), React.createElement("input", {
                          className: "border shadow table-cell",
                          id: "username-field",
                          name: "username",
                          type: "text",
                          value: match[0],
                          onChange: usernameChange
                        })), React.createElement("div", {
                      className: "m-4"
                    }, React.createElement("label", {
                          className: "table-cell text-black",
                          htmlFor: "password"
                        }, "Password: "), React.createElement("input", {
                          className: "border shadow table-cell",
                          id: "password-field",
                          name: "password",
                          type: "password",
                          value: match$1[0],
                          onChange: passwordChange
                        })), React.createElement("div", {
                      className: "m-4"
                    }, React.createElement("button", {
                          className: "text-black p-2 border align-end bg-gray-400",
                          id: "login-button"
                        }, "Login"))));
}

var LoginForm = {
  make: Login$LoginForm
};

function Login$LoginModal(Props) {
  return React.createElement("div", {
              className: "flex items-end justify-center "
            }, React.createElement(Login$LoginForm, {}));
}

var LoginModal = {
  make: Login$LoginModal
};

export {
  LoginForm ,
  LoginModal ,
  
}
/* react Not a pure module */
