// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Index from "./Index.bs.js";
import * as Login from "./Login.bs.js";
import * as React from "react";
import * as PageNotFound from "./PageNotFound.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function Main(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match) {
    if (match.hd === "login") {
      if (match.tl) {
        return React.createElement(PageNotFound.make, {});
      } else {
        return React.createElement(Login.LoginModal.make, {});
      }
    } else {
      return React.createElement(PageNotFound.make, {});
    }
  } else {
    return React.createElement(Index.make, {});
  }
}

var make = Main;

export {
  make ,
  
}
/* Index Not a pure module */
