// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function PageNotFound(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-black dark:text-white"
                }, "PAGE NOT FOUND."));
}

var make = PageNotFound;

export {
  make ,
  
}
/* react Not a pure module */
