// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function TableRow(Props) {
  var areaCode = Props.areaCode;
  var description = Props.description;
  var row = Props.row;
  var column = Props.column;
  return React.createElement("tr", undefined, React.createElement("td", undefined, areaCode), React.createElement("td", undefined, description), React.createElement("td", undefined, row), React.createElement("td", undefined, column));
}

var make = TableRow;

export {
  make ,
  
}
/* react Not a pure module */
