// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Index from "./components/Index.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

import '../styles/main.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Index.make, {}), root);
}

export {
  
}
/*  Not a pure module */
