// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Login from "./components/Login.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

import 'tailwindcss/tailwind.css'
;

import '../styles/main.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Login.LoginModal.make, {}), root);
}

export {
  
}
/*  Not a pure module */
