// Generated by ReScript, PLEASE EDIT WITH CARE


var setCookie = (function(name, value) {
    document.cookie = name + "=" + value + "; SameSite=Strict;";
  });

export {
  setCookie ,
  
}
/* No side effect */
