// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cookie from "rescript-cookie/src/Cookie.bs.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as JsCookie from "./JsCookie.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as Dom_storage from "rescript/lib/es6/dom_storage.js";

function getToken(param) {
  var header = Dom_storage.getItem("header", localStorage);
  var payload = Dom_storage.getItem("payload", localStorage);
  var jsCookie = JsCookie.getCookie(undefined);
  var cookie = Js_dict.get(Cookie.parse(jsCookie, undefined, undefined), "token-signature");
  var result = Belt_Array.keepMap([
        header,
        payload,
        cookie
      ], (function (x) {
          return x;
        }));
  if (result.length !== 0) {
    return Caml_array.get(result, 0) + "." + Caml_array.get(result, 1) + "." + Caml_array.get(result, 2);
  } else {
    return "";
  }
}

export {
  getToken ,
  
}
/* Cookie Not a pure module */
